---
- debug:
    msg: "Hello from your external use case!"

- set_fact:
    ingress_class: traefik
    required_extra_vars:
      - dt_oauth_sso_endpoint
      - dt_oauth_client_id
      - dt_oauth_client_secret
      - dt_oauth_account_urn
      - dt_environment_url_gen3

#####################
######## K3S ########
#####################
- include_role:
    name: k3s

###########################
######## EasyTrade ########
###########################
- include_role:
    name: app-easytrade
  vars:
    easytrade_namespace: "easytrade-app"
    easytrade_domain: "easytrade-app.{{ ingress_domain }}"
    easytrade_deploy: false
    easytrade_owner: "easytrade-hot-devs"
    easytrade_ingress_class: "traefik"

# - name: Template Easytrade Ingress Patch
#   template:
#     src: "{{ role_path }}/templates/easytrade-ingress.yml.j2"
#     dest: "{{ role_path }}/files/kustomize/overlays/app/easytrade-ingress.yml"
#     owner: "{{ ace_box_user }}"
#     group: "{{ ace_box_user }}"
#     mode: '0644'
#   vars:
#     easytrade_domain: "easytrade-app.{{ ingress_domain }}"

###########################
######## Dynatrace ########
###########################
# - name: Helm install operator
#   shell: |
#     helm install dynatrace-operator oci://public.ecr.aws/dynatrace/dynatrace-operator \
#     --set "imageRef.repository=gcr.io/dynatrace-marketplace-prod/dynatrace-operator" \
#     --create-namespace \
#     --namespace dynatrace \
#     --atomic \
#     --version 1.3.0-rc.0

# #
# # Apply Dynakube
# #
# - name: Template Dynakube manifest
#   ansible.builtin.template:
#     src: "applicationMonitoring-new.yaml.j2"
#     dest: "{{ role_path }}/files/applicationMonitoring-new.yaml"
#     owner: "{{ ace_box_user }}"
#     group: "{{ ace_box_user }}"
#     mode: "0644"
# - name: Apply Dynakube manifest
#   kubernetes.core.k8s:
#     state: present
#     src: "{{ role_path }}/files/applicationMonitoring-new.yaml"
#   register: dynakube
#   retries: 10
#   delay: 10
#   until: dynakube is not failed
